### ISSUE TITLE
Shockwave filter not supporting alpha

### ISSUE THREAD

**Issue by nasselk** [pixijs/filters#441] opened 2024-02-18 14:19 UTC
I noticed that the shockwave filters doesn't render normally when a sprite has an alpha under 1.

Here is a fiddle illustrating the problem : https://jsfiddle.net/pn5Lkjy3/

If you switch the waterSprite alpha to 1, it will display normally

**Comment by bigtimebuddy** [comment] 2024-02-19 15:13
Thanks for reporting. Duplicate of #443, adding more details over there.

**Closed by bigtimebuddy** 2024-02-19 15:13 UTC
