### ISSUE TITLE
Uncaught TypeError: class constructors must be invoked with 'new' using Shockwave filter

### ISSUE THREAD

**Issue by wolfiton** [pixijs/filters#381] opened 2023-04-03 20:56 UTC
Hello here is the code that reproduces the error from what I understand there is an issue with version 7 of Pixi and the filters plugin. So my question is:
Can this be fixed or I need to use version 6 of Pixi to be able to use the filter in my projects?

```js
const app = new PIXI.Application({
  height: window.innerHeight,
  width: window.innerWidth,
});

document.body.appendChild(app.view);

// create a sprite with an image

  const texture = await PIXI.Assets.load("./assets/images/sunset.jpg");

  // create a new Sprite from the awaited loaded Texture
  const sprite = PIXI.Sprite.from(texture);

  // center the sprite's anchor point
  sprite.anchor.set(0.5);

  // move the sprite to the center of the screen
  sprite.x = app.screen.width / 2;
  sprite.y = app.screen.height / 2;

  app.stage.addChild(sprite);

  // create a new ShockwaveFilter
  const shockwaveFilter = new PIXI.filters.ShockwaveFilter(
    {
      amplitude: 20, // the amplitude of the shockwave effect
      wavelength: 100, // the wavelength of the shockwave effect
      brightness: 1, // the brightness of the shockwave effect
      speed: 500, // the speed of the shockwave effect
    }
  );

  // apply the shockwave filter to the sprite
  sprite.filters = [shockwaveFilter];

  // animate the shockwave filter by updating the center property
  app.ticker.add(() => {
    // update the center of the shockwave filter
    shockwaveFilter.center = [
      sprite.x + sprite.width / 2,
      sprite.y + sprite.height / 2,
    ];
  });
```
Thank you in advance for your time

**Comment by bigtimebuddy** [comment] 2024-08-18 17:56
Duplicate of #379

**Closed by bigtimebuddy** 2024-08-18 17:56 UTC
