### ISSUE TITLE
DropShadowFilter edges are straightened

### ISSUE THREAD

**Issue by defpis** [pixijs/filters#289] opened 2021-03-30 06:39 UTC
![image](https://user-images.githubusercontent.com/48018016/112944627-ac195d80-9165-11eb-86f0-1e7ac6da7848.png)

**Comment by defpis** [comment] 2021-03-30 06:41
`const g = new PIXI.Graphics();
const shadowOptions = {
  distance: 100,
  // blur: 4,
  // quality: 3,
  // alpha: 0.5,
  // shadowOnly: true
};
const f = new DropShadowFilter(shadowOptions);
g.filters = [f];

g.beginFill(0xff0000).drawCircle(0, 0, 100).endFill();
stage.addChild(g);

ticker.add(() => {
  stage.position.set(transform.x, transform.y);
  stage.scale.set(transform.z, transform.z);

  // f.blur = shadowOptions.blur * transform.z;
  // f.distance = shadowOptions.distance * transform.z;

  g.position.set(screen.width / 2, screen.height / 2);
});
`

**Comment by defpis** [comment] 2021-03-30 06:48
Somebody know how to resolve it?

**Comment by bigtimebuddy** [comment] 2021-03-31 00:03
I cannot reproduce: https://jsfiddle.net/bigtimebuddy/z4pr0gcf/

Please make a functional version of this to make it easier to debug.

**Comment by defpis** [comment] 2021-04-02 04:09
I modified your example with follow codes, and then the problem appeared
```
- g.position.set(app.screen.width / 2, app.screen.height / 2);
+ g.position.set(app.screen.width / 2, 0);
```
example: https://jsfiddle.net/1eto73um/2/

**Comment by defpis** [comment] 2021-04-02 04:12
I have located the problem, configure `autoFit = false` for DropShadowFilterOptions can solve it.

**Comment by bigtimebuddy** [comment] 2021-05-20 20:01
Closing this as it seems solved.

**Closed by bigtimebuddy** 2021-05-20 20:01 UTC
